import tkinter
from tkinter import *
import pymysql
from tkinter import messagebox
from database.mysql_connector import get_connection
def comp_insert_scr():
    t=tkinter.Tk()
    t.geometry('800x800')
    t.title('COMPANY MASTER')
    x=Canvas(t,height=800,width=800,bg='salmon1')
    x.place(x=1,y=1)
    def savedata():
        db=get_connection()
        cur=db.cursor()
        xa=int(b.get())
        xb=e.get()
        xc=g.get()
        xd=j.get()
        xe=m.get()
        xf=(p.get())
        sql="insert into comp_master values(%d,'%s','%s','%s','%s','%s')"%(xa,xb,xc,xd,xe,xf)
        cur.execute(sql)
        db.commit()
        b.delete(0,100)
        e.delete(0,100)
        g.delete(0,100)
        j.delete(0,100)
        m.delete(0,100)
        p.delete(0,100)
        db.close()
        messagebox.showinfo('Hi','Saved')
    def cm():
        t.destroy()
        
    aa=Label(t,text='INSERT DATA',font=('algerian',20),bg='salmon1')    
    aa.place(x=250,y=50)    
    a=Label(t,text='Company id',bg='salmon1')
    a.place(x=50,y=100)
    b=Entry(t,width=20)
    b.place(x=400,y=100)
    d=Label(t,text='Name',bg='salmon1')
    d.place(x=50,y=140)
    e=Entry(t,width=20)
    e.place(x=400,y=140)
    f=Label(t,text='Address',bg='salmon1')
    f.place(x=50,y=180)
    g=Entry(t,width=20)
    g.place(x=400,y=180)
    h=Label(t,text='Email',bg='salmon1')
    h.place(x=50,y=220)
    j=Entry(t,width=20)
    j.place(x=400,y=220)
    k=Label(t,text='Phone no',bg='salmon1')
    k.place(x=50,y=260)
    m=Entry(t,width=20)
    m.place(x=400,y=260)
    n=Label(t,text='Registration no',bg='salmon1')
    n.place(x=50,y=300)
    p=Entry(t,width=20)
    p.place(x=400,y=300)
    r=Button(t,text='Save',command=savedata,bg='peachpuff')
    r.place(x=250,y=400)
    u=Button(t,text='Close',command=cm,bg='peachpuff')
    u.place(x=350,y=400)
    
    t.mainloop()
